language: node_js
node_js:
  - "4.1"
sudo: required
services:
  - docker
  - postgresql
before_script:
  - psql -c 'create database jenca-authorisation;' -U postgres
  - node_modules/.bin/pg-migrate up
install:
  - make developer
  - npm install
  - make ci
# Post to Slack
notifications:
  slack: jencateam:m1Z9iUkUDDtl77hoUlm4SQEb

